<?xml version="1.0"?>
<package format="3">
  <name>light_test</name>
  <version>0.1.0</version>
  <description>Minimal Master 2 axis 0 EtherCAT test.</description>
  <maintainer email="niic@example.com">niic</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>control_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
